2021-02-14 21:37:48,848 ERROR    Uncaught exception: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ilab/users/wjw62/pa1/autograde.py", line 953, in main
    test_project(assignment, src_dir, build_dir, data_dir, **kws)
  File "/ilab/users/wjw62/pa1/autograde.py", line 734, in test_project
    (success, credit) = t.run()
  File "/ilab/users/wjw62/pa1/autograde.py", line 159, in run
    self.handle_stdin(p.stdin)
  File "/ilab/users/wjw62/pa1/autograde.py", line 371, in handle_stdin
    stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
